### PR TITLE
Milestone 1: Created Heatmap of Smashing Magaine website

### PR DESCRIPTION
**Pull request by aecordova**
In this milestone we:
- Added readme file.
- Added HTML file
- Added CSS Styling
- Reviewed files with Linter and W3 validator.

### CODE REVIEW

**Comment by shshamim63** [comment]
## Status :recycle: [!! Required Changes !!]
___
Hi @aecordova and @moinkhanif :wave: ,
Awesome job :clap: . Code looks neat and clean. Well descriptive readme. No error on HTML markup validation. Stickler is working properly. But just one postion of rendering is just blocking me. And I am sure that you will cover it easily.  :sunglasses: 
___
### :spades: [Mandatory Changes] :spades: 
___
1. This three articles should contain equal width. But your one is not containing it. cause of grid-template-columns: repeat(4, 1fr); I think it should be 3 instead of 4.
image
___
#### Please fix the above mentioned issue and send another review request.
___
## :gear: Happy Coding :gear: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](Shakhawat Hossain)

**Comment by moinkhanif** [comment]
Hey @shshamim63 , thanks for pointing that out. It had to be a 4 columned grid because we were using span on two columns and the rest were individual articles in the next line just like the one in the original smashing magazine website. So I just removed the margin-left from the first article and changed the color of the h3 to get an equal width and better look.

**Comment by shshamim63** [comment]
## Status :green_apple: : [!! Required Changes !!]
___
Hi @aecordova and @moinkhanif :wave: ,
I have checked the original page and I can see the below one
image
Where each of them are equal in width. But your one is not rendering like that. Cause of 4 columned grid.
And on your one->
image
Well I think if you separate the grid column for each section that will be the more beneficial.
___
#### Please fix the above mentioned issue and send another review request.
___
## :gear: Happy Coding :gear: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](Shakhawat Hossain)

**Comment by moinkhanif** [comment]
Heya @shshamim63 , smashing magazine had media queries for various screen sizes and hence we had different columns. I fixed the issue by adding the required queries. Thank you. 😄

**Comment by Anna-Myzukina** [comment]
#### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi team!

### Nice job! Project looks! :+1: WOW  the readme file is very descriptive!

### But your project still needs changes.

- Kindly recommended checking HTML markup with this validator https://validator.w3.org/#validate_by_upload.



Now it shows error in your project



- Footer should contain centered links  ([link to page](https://www.smashingmagazine.com/))

- Please remember that Pull Request should have meaningful title and a short description screenshot You can read more here [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/). Hope you can o it in next projects.

- Comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history screenshot from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)
### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
The project still needs changes

**Comment by aecordova** [comment]
Hi @Anna-Myzukina, I just changed the title and the description comment of this pull request as per your suggestion. In regards to the footer, all boxes representing links are centered.
please see image:
image

**Review by nikasulo — APPROVED** [review]
Great job @aecordova and @moinkhanif :rocket: 
You may merge! :handshake: .

**Pull request merged**
